<<<<<<< HEAD
title: no style, please! # name of the site
author: Riccardo Graziosi # name of site's author
email: riccardo.graziosi97@gmail.com # email of site's author
url: https://riggraz.dev # root address of the site
baseurl: "/no-style-please" # subpath of the site, e.g. "/blog"
description: > # description of the site (multiple lines allowed)
  A (nearly) no-CSS, fast, minimalist Jekyll theme.
=======
title: Study Blog # The title of the blog
author: Jiwon-JJW # Your name 
email: znfhdnal1@gmail.com # your email shown in the footer
url: https://jiwon-jjw.github.io/ # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  정리한 것들을 올려요
favicon: "./favicon.ico" # set the favicon of the site 
>>>>>>> 9cf7ddb14aefd8b5e90b90ca24ba60b8204139aa

permalink: /:slug.html

<<<<<<< HEAD
favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics
=======
  # generate social links in about page.
  social_links:
    # twitter: 
    github:  Jiwon-JJW
    rss: RSS
    # dribbble: 
   # facebook: huangyz0918
    # flickr:   
    # instagram: 
   # linkedin: yizheng-huang
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 
>>>>>>> 9cf7ddb14aefd8b5e90b90ca24ba60b8204139aa

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag